/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./storage/framework/views/*.php",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
                serif: ['Georgia', 'Cambria', 'Times New Roman', 'Times', 'serif'],
                mono: ['SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
            },
            colors: {
                primary: {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    300: '#93c5fd',
                    400: '#60a5fa',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    800: '#1e40af',
                    900: '#1e3a8a',
                    950: '#172554',
                },
                secondary: {
                    50: '#f8fafc',
                    100: '#f1f5f9',
                    200: '#e2e8f0',
                    300: '#cbd5e1',
                    400: '#94a3b8',
                    500: '#64748b',
                    600: '#475569',
                    700: '#334155',
                    800: '#1e293b',
                    900: '#0f172a',
                    950: '#020617',
                },
                success: {
                    50: '#f0fdf4',
                    100: '#dcfce7',
                    200: '#bbf7d0',
                    300: '#86efac',
                    400: '#4ade80',
                    500: '#22c55e',
                    600: '#16a34a',
                    700: '#15803d',
                    800: '#166534',
                    900: '#14532d',
                    950: '#052e16',
                },
                warning: {
                    50: '#fffbeb',
                    100: '#fef3c7',
                    200: '#fde68a',
                    300: '#fcd34d',
                    400: '#fbbf24',
                    500: '#f59e0b',
                    600: '#d97706',
                    700: '#b45309',
                    800: '#92400e',
                    900: '#78350f',
                    950: '#451a03',
                },
                danger: {
                    50: '#fef2f2',
                    100: '#fee2e2',
                    200: '#fecaca',
                    300: '#fca5a5',
                    400: '#f87171',
                    500: '#ef4444',
                    600: '#dc2626',
                    700: '#b91c1c',
                    800: '#991b1b',
                    900: '#7f1d1d',
                    950: '#450a0a',
                },
            },
            spacing: {
                '18': '4.5rem',
                '88': '22rem',
                '128': '32rem',
                '144': '36rem',
            },
            maxWidth: {
                '8xl': '88rem',
                '9xl': '96rem',
            },
            minHeight: {
                '10': '2.5rem',
                '12': '3rem',
                '16': '4rem',
                '20': '5rem',
                '24': '6rem',
            },
            zIndex: {
                '60': '60',
                '70': '70',
                '80': '80',
                '90': '90',
                '100': '100',
            },
            animation: {
                'fade-in': 'fadeIn 0.5s ease-in-out',
                'fade-out': 'fadeOut 0.5s ease-in-out',
                'slide-up': 'slideUp 0.3s ease-out',
                'slide-down': 'slideDown 0.3s ease-out',
                'slide-left': 'slideLeft 0.3s ease-out',
                'slide-right': 'slideRight 0.3s ease-out',
                'bounce-in': 'bounceIn 0.6s ease-out',
                'pulse-slow': 'pulse 3s infinite',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                fadeOut: {
                    '0%': { opacity: '1' },
                    '100%': { opacity: '0' },
                },
                slideUp: {
                    '0%': { transform: 'translateY(100%)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideDown: {
                    '0%': { transform: 'translateY(-100%)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideLeft: {
                    '0%': { transform: 'translateX(100%)', opacity: '0' },
                    '100%': { transform: 'translateX(0)', opacity: '1' },
                },
                slideRight: {
                    '0%': { transform: 'translateX(-100%)', opacity: '0' },
                    '100%': { transform: 'translateX(0)', opacity: '1' },
                },
                bounceIn: {
                    '0%': { transform: 'scale(0.3)', opacity: '0' },
                    '50%': { transform: 'scale(1.1)', opacity: '1' },
                    '70%': { transform: 'scale(0.9)' },
                    '100%': { transform: 'scale(1)' },
                },
            },
            typography: (theme) => ({
                DEFAULT: {
                    css: {
                        color: theme('colors.gray.700'),
                        maxWidth: 'none',
                        h1: {
                            color: theme('colors.gray.900'),
                            fontWeight: '700',
                            fontSize: theme('fontSize.3xl')[0],
                            marginBottom: theme('spacing.4'),
                        },
                        h2: {
                            color: theme('colors.gray.900'),
                            fontWeight: '600',
                            fontSize: theme('fontSize.2xl')[0],
                            marginBottom: theme('spacing.3'),
                            marginTop: theme('spacing.6'),
                        },
                        h3: {
                            color: theme('colors.gray.900'),
                            fontWeight: '500',
                            fontSize: theme('fontSize.xl')[0],
                            marginBottom: theme('spacing.2'),
                            marginTop: theme('spacing.4'),
                        },
                        p: {
                            marginBottom: theme('spacing.4'),
                            lineHeight: '1.75',
                        },
                        a: {
                            color: theme('colors.primary.600'),
                            textDecoration: 'none',
                            '&:hover': {
                                color: theme('colors.primary.800'),
                            },
                        },
                        blockquote: {
                            borderLeftColor: theme('colors.gray.300'),
                            borderLeftWidth: '4px',
                            paddingLeft: theme('spacing.4'),
                            fontStyle: 'italic',
                            marginBottom: theme('spacing.4'),
                        },
                        code: {
                            backgroundColor: theme('colors.gray.100'),
                            padding: `${theme('spacing.1')} ${theme('spacing.1')}`,
                            borderRadius: theme('borderRadius.DEFAULT'),
                            fontSize: theme('fontSize.sm')[0],
                            fontFamily: theme('fontFamily.mono').join(', '),
                        },
                        pre: {
                            backgroundColor: theme('colors.gray.900'),
                            color: theme('colors.white'),
                            padding: theme('spacing.4'),
                            borderRadius: theme('borderRadius.lg'),
                            overflowX: 'auto',
                            marginBottom: theme('spacing.4'),
                            code: {
                                backgroundColor: 'transparent',
                                padding: '0',
                            },
                        },
                        'ul, ol': {
                            marginBottom: theme('spacing.4'),
                            paddingLeft: theme('spacing.6'),
                        },
                        li: {
                            marginBottom: theme('spacing.1'),
                        },
                    },
                },
            }),
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/aspect-ratio'),
    ],
}